# Generated by Django 5.0.6 on 2024-05-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='mikrotik_ip',
            new_name='mikrotik_IP',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='sessien_name',
            new_name='session_name',
        ),
    ]
