# Generated by Django 5.0.6 on 2024-05-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_session_dns_name_session_hotspot_server_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uptime', models.CharField(max_length=8)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.session')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.session')),
            ],
        ),
    ]
