# Generated by Django 5.0.6 on 2024-06-02 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uptime_format',
            field=models.CharField(choices=[('s', 'second'), ('m', 'minute'), ('h', 'hour'), ('d', 'day')], default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='dashboard.session'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uptime',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.profile'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_session', to='dashboard.session'),
        ),
    ]
