# Generated by Django 5.0.6 on 2024-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_uptime_format_alter_profile_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uptime_format',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi opsional untuk profil ini', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='download_limit_unit',
            field=models.CharField(choices=[('K', 'Kbps'), ('M', 'Mbps'), ('G', 'Gbps')], default=0, help_text='Unit batas kecepatan download (Kbps, Mbps, Gbps)', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='download_limit_value',
            field=models.PositiveIntegerField(default=1, help_text='Nilai batas kecepatan download (misalnya, 1024 untuk 1 Mbps)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default=1, help_text='Nama unik untuk profil rate limit', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='shared_users',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah maksimum pengguna yang dapat berbagi profil ini'),
        ),
        migrations.AddField(
            model_name='profile',
            name='upload_limit_unit',
            field=models.CharField(choices=[('K', 'Kbps'), ('M', 'Mbps'), ('G', 'Gbps')], default=1, help_text='Unit batas kecepatan upload (Kbps, Mbps, Gbps)', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='upload_limit_value',
            field=models.PositiveIntegerField(default=1, help_text='Nilai batas kecepatan upload (misalnya, 512 untuk 512 Kbps)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='uptime_unit',
            field=models.CharField(choices=[('s', 'second'), ('m', 'minute'), ('h', 'hour'), ('d', 'day')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='uptime_value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
