# Generated by Django 5.0.6 on 2024-06-04 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_profile_name_remove_profile_uptime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='download_limit_unit',
            field=models.CharField(choices=[('K', 'Kbps'), ('M', 'Mbps')], help_text='Unit batas kecepatan download (Kbps, Mbps, Gbps)', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='download_limit_value',
            field=models.IntegerField(help_text='Nilai batas kecepatan download (misalnya, 1024 untuk 1 Mbps)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(help_text='Nama unik untuk profil rate limit', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_session', to='dashboard.session'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shared_users',
            field=models.IntegerField(default=1, help_text='Jumlah maksimum pengguna yang dapat berbagi profil ini', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload_limit_unit',
            field=models.CharField(choices=[('K', 'Kbps'), ('M', 'Mbps')], help_text='Unit batas kecepatan upload (Kbps, Mbps, Gbps)', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload_limit_value',
            field=models.IntegerField(help_text='Nilai batas kecepatan upload (misalnya, 512 untuk 512 Kbps)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='uptime_unit',
            field=models.CharField(choices=[('s', 'second'), ('m', 'minute'), ('h', 'hour'), ('d', 'day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='uptime_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='VoucherPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_pdf_session', to='dashboard.session')),
            ],
        ),
    ]
