# Generated by Django 5.0.6 on 2024-06-07 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_profile_download_limit_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='checkout_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
