# Generated by Django 5.0.6 on 2024-06-10 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_voucher_checkout_date_voucher_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='price',
            new_name='price_min',
        ),
        migrations.AddField(
            model_name='voucher',
            name='price_max',
            field=models.IntegerField(default=20000, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
