# Generated by Django 5.0.6 on 2024-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_price_voucher_price_min_voucher_price_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpdf',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
